[project]
name = "lodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "boto3>=1.37.1",
  "dvc[s3]>=3.59.1",
  "geopandas>=1.0.1",
  "pandas>=2.2.3",
  "requests>=2.32.3",
]
