baseURL = "https://lodesmap.com/"
languageCode = "en-us"
title = "LODES Map"
disableKinds = ["taxonomy", "term"]
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.goldmark.extensions]
  linkify = false

[params]
  description = "Origin and Destination Job Data"
  author = "John Johnson & Mitchell Henke"
