---

name: Install DVC
description: Installs Python and DVC with S3 support

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-suffix: "dvc"

    - name: Install DVC
      id: install_python_deps
      shell: bash
      run: |
        uv python install
        uv venv
        uv pip install "dvc[s3]"
